/* eslint-disable @typescript-eslint/no-floating-promises */
import Head from "next/head";
import ChannelsBar from "@/components/ChannelsBar/ChannelsBar";
import { Fragment, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { observer } from "mobx-react";
import Pop from "utils/Pop";
import ServerMembersBar from "@/components/MembersBar/ServerMembersBar";
import { AppState } from "AppState";
import { setRedirect } from "utils/Redirect";
import { channelsService, messageService, serversService } from "@/services";
import { withAuth, withMember } from "@/middleware";
import TopNavigation from "@/components/Messages/TopNavigation";
import MessageScroll from "@/components/Messages/MessageScroll";
import CreateMessage from "@/components/CreateMessage/CreateMessage";
import { NextPage } from "next";

const ServerOne: NextPage = () => {
  const router = useRouter();
  const {id, channel} = router.query as {id:string; channel:string};
  // const serverId = router.query.id as string;
  // const channelId = router.query.channel as string;
  useEffect(() => {
    if (!id || !channel) {
      return;
    }

    const fetchServerData = async () => {
      try {
        // AppState.messages = [];
        // AppState.messageLikes = [[]];

        await channelsService.getChannelsByServerId(id);

        await messageService.getMessagesByChannelId(channel);

        // await serversService.getMembers(id);
        console.log(AppState.messages);
      } catch (error) {
        Pop.error(error);
      }
    };
    fetchServerData();
  }, [id, channel]);

  return (
    <>
      <Head>
        <title>next-pocket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex  h-screen w-full  ">
          <ChannelsBar />
          <div className=" message-container ">
            <TopNavigation />

            <MessageScroll />
            <CreateMessage />
          </div>
          <ServerMembersBar />
        </div>
      </main>
    </>
  );
};

export default observer(withAuth(withMember(ServerOne)));
