import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SideBar from '../../components/SideBar'
import ChannelsBar from '../../components/ChannelsBar'
import ContentContainer from '../../components/ContentContainer'
import React, {useEffect} from "react";
import { useRouter } from "next/router";
import { AppState } from "../../AppState";
const Home: NextPage = () => {
  // const router = useRouter();

  // useEffect(() => {
  //   const user = AppState?.user;
  //   if (!user) {
  //     router.push("/login");
  //   }
  // }, []);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex  w-full ">
          
       <SideBar />
       <ChannelsBar/>
       <ContentContainer/>
        </div>
      </main>
    </>
  );
};

export default Home;
