// Generated by ts-to-zod
import {  z } from "zod";
import {
  Collections,
  FileUploadsStatusOptions,
  FriendRequestStatusOptions,
} from "./pocketbase-types";

export const collectionsSchema = z.nativeEnum(Collections);

export const isoDateStringSchema = z.string();

export const recordIdStringSchema = z.string();

export const hTMLStringSchema = z.string();

export const channelsRecordSchema = z.object({
  members: z.array(recordIdStringSchema).optional(),
  messages: z.array(recordIdStringSchema).optional(),
  title: z.string().optional(),
  server: recordIdStringSchema.optional(),
});

export const directMessagesRecordSchema = z.object({
  from: recordIdStringSchema,
  to: recordIdStringSchema,
  text: z.string(),
  files: z.array(z.string()).optional(),
});

export const fileUploadsStatusOptionsSchema = z.nativeEnum(
  FileUploadsStatusOptions
);

export const fileUploadsRecordSchema = z.object({
  file: z.array(z.string()).optional(),
  url: z.string().optional(),
  user: recordIdStringSchema,
  status: fileUploadsStatusOptionsSchema.optional(),
});

export const friendRequestStatusOptionsSchema = z.nativeEnum(
  FriendRequestStatusOptions
);

export const friendRequestRecordSchema = z.object({
  senderId: recordIdStringSchema,
  receiverId: recordIdStringSchema,
  status: friendRequestStatusOptionsSchema.optional(),
  field: z.string().optional(),
});

export const friendsRecordSchema = z.object({
  user: recordIdStringSchema,
  friends: z.array(recordIdStringSchema).optional(),
});

export const likesRecordSchema = z.object({
  message: recordIdStringSchema,
  liked: z.boolean().optional(),
  user: recordIdStringSchema,
});

export const membersRecordSchema = z.object({
  user: recordIdStringSchema,
  server: recordIdStringSchema,
});

export const messagesRecordSchema = z.object({
  user: recordIdStringSchema,
  channel: recordIdStringSchema.optional(),
  content: hTMLStringSchema.optional(),
});

export const serversRecordSchema = z.object({
  image: recordIdStringSchema.optional(),
  name: z.string(),
  description: z.string().optional(),
  members: z.array(recordIdStringSchema).optional(),
  owner: recordIdStringSchema.optional(),
});

export const usersRecordSchema = z.object({
  currentChannel: recordIdStringSchema.optional(),
  avatar: z.string().optional(),
  avatarUrl: z.string().optional(),
});

export const usersStatusRecordSchema = z.object({
  isOnline: z.boolean().optional(),
  user: recordIdStringSchema,
});

export const collectionRecordsSchema = z.object({
  channels: channelsRecordSchema,
  directMessages: directMessagesRecordSchema,
  fileUploads: fileUploadsRecordSchema,
  friendRequest: friendRequestRecordSchema,
  friends: friendsRecordSchema,
  likes: likesRecordSchema,
  members: membersRecordSchema,
  messages: messagesRecordSchema,
  servers: serversRecordSchema,
  users: usersRecordSchema,
  usersStatus: usersStatusRecordSchema,
});
