/* eslint-disable @typescript-eslint/no-floating-promises */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SideBar from "../../components/SideBar/SideBar";
import ChannelsBar from "../../components/Channels/ChannelsBar";
import ContentContainer from "../../components/Messages/MessageContainer";
import React, { useEffect } from "react";
import { useRouter } from "next/router";
import { AppState } from "../../../AppState";
import { authsService } from "../../services/AuthsService";
import { pb } from "../../../utils/pocketBase";
import ServerMembersBar from "../../components/MembersBar/ServerMembersBar";
import { serversService } from "../../services/ServersService";
const Server: NextPage = () => {
  const router = useRouter();
  console.log(router.query)
  useEffect(() => {
    const user = pb.authStore.model;
    if (!user) {
      router.push("/login");
    }
  }, [router]);


// useEffect(()=>{
//     const user : object | null = pb.authStore.model;
// const getServerByUserId = async () =>{
//   await serversService.getUserServers(user.id)

// }
// getServerByUserId()

// },[])

  return (
    <>
      <Head>
        <title>next-pocket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex  w-full ">
          {/* <SideBar /> */}
          <ChannelsBar />
          <ContentContainer />
          <ServerMembersBar />
        </div>
      </main>
    </>
  );
};



export default Server;
