/* eslint-disable @typescript-eslint/no-floating-promises */
import { type NextPage } from "next";
import Head from "next/head";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { AppState } from "../../../AppState";

import { pb } from "../../../utils/pocketBase";
import { ServersResponse } from "../../../PocketBaseTypes/pocketbase-types";
import { observer } from "mobx-react";
import FriendsBar from "../../components/DirectMessages/FriendsBar";
import Pop from "../../../utils/Pop";
import { directMessageService } from "../../services/DirectMessagesService";

import DirectMessageContainer from "../../components/DirectMessages/DirectMessageContainer";
const DirectMessagesId: NextPage = () => {
  const router = useRouter();
  const id = router.query.id as string;
  const user = AppState.user;

  useEffect(() => {
    if (!user) {
      router.push("/login");
    }

    if (router.query.id) {
      const fetchMessages = async () => {
        try {
          const res = await directMessageService.getDirectMessages(
            user!.id,
            id
          );

          // AppState.activeDirectMessage = res.find(a => a.expand.from && a.expand.)
        } catch (error) {
          Pop.error(error);
        }
      };
      fetchMessages();
    }
  }, [router.query.id]);

  return (
    <>
      <Head>
        <title>next-pocket</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex  h-screen   w-full ">
          <FriendsBar />

          <DirectMessageContainer />
        </div>
      </main>
    </>
  );
};

export default observer(DirectMessagesId);
